### ISSUE TITLE
error when updating from 3.0.0 to 5.2.8

### ISSUE THREAD

**Issue by cfthompson** [Digitalist-Open-Cloud/Matomo-Plugin-BotTracker#1]
I'm running matomo in a Fargate container in AWS, talking to an RDS database, and I'm getting the followng error in Cloudwatch logs when I try to launch the container with the 5.2.8 version of this plugin.  It seems to be perfectly happy when I roll it back to 3.0.0.  Was there a script to update the schema that I missed somehow?

[Thu Mar 28 00:56:00.222468 2024] [php:notice] [pid 77] [client 172.30.1.86:39950] [172.30.42.19] Error in Matomo: There was a problem installing the plugin BotTracker:                  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;Monitoring &amp; Analytics&#039; for key &#039;matomo_bot_type.name&#039;                                  If you want to hide this message you must remove the following line under the [Plugins] entry in your                 'config/config.ini.php' file to disable this plugin.                 Plugins[] = BotTracker                 If this plugin has already been installed, you must add the following line under the                 [PluginsInstalled] entry in your 'config/config.ini.php' file:                 PluginsInstalled[] = BotTracker

**Comment by mikkeschiren** [comment]
The schema is updated with running ./console core:update. Though I can't really figure out why that error happened. I will look into it.

**Comment by mikkeschiren** [comment]
matomo_bot_type is created on the update, there should be only one entry created for that row:

```
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Monitoring & Analytics']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Search Engine Optimization']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Advertising & Marketing']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Page Preview']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Webhook']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Social network']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Scraper']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Copyright']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Search Engine Crawler']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'AI Search Crawler']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'AI Data Scraper']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'AI Assistant']);
        $migrations[] = $this->migration->db->insert('bot_type', ['name' => 'Other']);
```

**Comment by mikkeschiren** [comment]
Could you look into the table and see if you have double entries?

**Comment by cfthompson** [comment]
This is what I have currently, using BotTracker 3.0.0.  If you'd like to see what the table looks like after I attempt an upgrade, I'll have to break it again, and the powers that be prefer that I do that after hours.
```
mysql> select * from matomo_bot_type;
+----+----------------------------+---------------------+
| id | name                       | date                |
+----+----------------------------+---------------------+
|  1 | Monitoring & Analytics     | 2024-03-24 19:40:36 |
|  2 | Search Engine Optimization | 2024-03-24 19:40:36 |
|  4 | Advertising & Marketing    | 2024-03-24 19:40:36 |
|  5 | Page Preview               | 2024-03-24 19:40:36 |
|  6 | Webhook                    | 2024-03-24 19:40:36 |
|  7 | Social network             | 2024-03-24 19:40:36 |
|  8 | Scraper                    | 2024-03-24 19:40:36 |
|  9 | Copyright                  | 2024-03-24 19:40:36 |
| 10 | Search Engine Crawler      | 2024-03-24 19:40:36 |
| 11 | AI Search Crawler          | 2024-03-24 19:40:36 |
| 12 | AI Data Scraper            | 2024-03-24 19:40:36 |
| 13 | AI Assistant               | 2024-03-24 19:40:36 |
| 14 | Other                      | 2024-03-24 19:40:36 |
+----+----------------------------+---------------------+
13 rows in set (0.03 sec)

mysql>
```

**Comment by martinhaye** [comment]
Maybe it's trying to re-do a migration that's actually already been done?

**Comment by mikkeschiren** [comment]
That table doesn't exist in v3.0.0. It was added in v.5.1.0. So I think it's like what @martinhaye is saying.

**Comment by mikkeschiren** [comment]
What version do you get if you check in the db?
`SELECT * FROM matomo_option WHERE option_name like 'version_BotTracker';`

**Comment by cfthompson** [comment]
Looks like it at least thinks it's 3.0.0 still:
```
mysql> SELECT * FROM matomo_option WHERE option_name like 'version_BotTracker';
+--------------------+--------------+----------+
| option_name        | option_value | autoload |
+--------------------+--------------+----------+
| version_BotTracker | 3.0.0        |        1 |
+--------------------+--------------+----------+
1 row in set (0.03 sec)

mysql> 
```

**Comment by cfthompson** [comment]
So I guess what happened is that we tried upgrading multiple plugins at once, got errors, then rolled back the zip files for all of the plugins, but not the database.  So the BotTracker upgrade attempt would have updated the schema, and nothing would have undone that when we rolled back, so now when we try again, it tries to update the schema again and we run into this error because the table already exists.  I guess we should drop the table?

**Comment by mikkeschiren** [comment]
I would drop the table matomo_bot_type.

**Comment by cfthompson** [comment]
That seems to have done the trick.  No errors in the console or the log after the upgrade, and both the console and the database are telling me we're at 5.2.8 now.  I guess the way we found ourselves in this mess is by attempting to upgrade multiple plugins at once, and then rolling back all of them, but not the database, when one of them failed and we didn't know which.  It sounds like we're the only customers silly enough to have done something like that, so I guess we can close this issue.  Thanks for your help!

**Comment by mikkeschiren** [comment]
Great that it worked! Closing this issue.
