### ISSUE TITLE
PHP Warning:  Undefined array key "track_device_detector_bots"

### ISSUE THREAD

**Issue by webian** [Digitalist-Open-Cloud/Matomo-Plugin-BotTracker#12]
Since a couple of minor updates (now on 5.2.10) I get many warings in PHP 8.1 error log:
[11-Apr-2024 05:50:06 UTC] PHP Warning:  Undefined array key "track_device_detector_bots" in /var/www/matomo/plugins/BotTracker/BotTracker.php on line 304

**Comment by mikkeschiren** [comment]
yeah, noticed that one, in next release, we will solve this. it was missed during the testing.

**Comment by mikkeschiren** [comment]
Fixed in commit: https://github.com/digitalist-se/BotTracker/commit/de96e4d99d36400513310df658b975f03ade6685 in release 5.2.11.
